[package]
name = "voxels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.15.0", features = [ "derive" ] }
env_logger = "0.11.3"
glam = "0.27.0"
log = "0.4.21"
pollster = "0.3.0"
serde = { version = "1.0", features = [ "derive" ] }
thiserror = "1.0.61"
toml = "0.8.14"
wgpu = "0.20.0"
winit = "0.30.0"
